# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b723e4bd3c0a3e5f67b3981d84497865e9c288ab8ab26513b66c41c2542d96ec6b580544e1f5ca2003f1b7e9dc544dadad8789b511fcf77a9a2e682b847191

test:
  secret_key_base: 4e00920559130a3f4d4f957f39175709cc30f57c682f333339f74bcdf756533d8821d5b1e701ad5331e424cc01f3efd7cf1e7ad3aa7ec49f3140e419837e2c97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
